-- ========================================================
-- Supabase (PostgreSQL) Database Schema for IUDEX Portfolio
-- ========================================================
-- Copy and run this script in the Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql

-- 1. Create table 'user' (quoted as "user" in PostgreSQL)
CREATE TABLE IF NOT EXISTS public."user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create table 'projects'
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    admin VARCHAR(50) NOT NULL,
    tag VARCHAR(50) DEFAULT 'Digital Art',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    image VARCHAR(255) DEFAULT NULL,
    view_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure tag and view_count columns exist if table was created earlier
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS tag VARCHAR(50) DEFAULT 'Digital Art';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS view_count INT DEFAULT 0;

-- 3. Create table 'site_analytics'
CREATE TABLE IF NOT EXISTS public.site_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_path VARCHAR(255) NOT NULL,
    visitor_id VARCHAR(100) NOT NULL,
    country VARCHAR(100) DEFAULT 'Indonesia',
    duration_seconds INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Initial Seed Data for 'user'
INSERT INTO public."user" (username, password) 
VALUES
    ('imyusi', '99qr'),
    ('bilqis', 'qwerty123'),
    ('aliya', 'qwerty111')
ON CONFLICT (username) DO NOTHING;

-- 5. Enable Row Level Security (RLS) policies
ALTER TABLE public."user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_analytics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to projects" ON public.projects;
CREATE POLICY "Allow public read access to projects" ON public.projects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to user" ON public."user";
CREATE POLICY "Allow public read access to user" ON public."user" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert to site_analytics" ON public.site_analytics;
CREATE POLICY "Allow public insert to site_analytics" ON public.site_analytics FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read to site_analytics" ON public.site_analytics;
CREATE POLICY "Allow public read to site_analytics" ON public.site_analytics FOR SELECT USING (true);

