-- ========================================================
-- Supabase (PostgreSQL) Database Schema for IUDEX Portfolio
-- ========================================================
-- Copy and run this script in the Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql

-- 1. Create table 'user' (quoted as "user" in PostgreSQL)
CREATE TABLE IF NOT EXISTS public."user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create table 'projects'
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    admin VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    image VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Initial Seed Data for 'user'
INSERT INTO public."user" (username, password) 
VALUES
    ('imyusi', '99qr'),
    ('bilqis', 'qwerty123'),
    ('aliya', 'qwerty111')
ON CONFLICT (username) DO NOTHING;

-- 4. Sample Seed Data for 'projects'
INSERT INTO public.projects (title, description, admin, date, image)
VALUES
    ('Project Portfolio Sidik', 'Deskripsi portofolio utama Sidik.', 'Sidik', CURRENT_DATE, 'public/uploads/sidik_porto/DA_galeri1.png'),
    ('Project Portofolio Aliya', 'Deskripsi portofolio utama Aliya.', 'Aliya', CURRENT_DATE, 'public/uploads/aliya/aliyafoto.jpg'),
    ('Project Portofolio Bilqis', 'Deskripsi portofolio utama Bilqis.', 'Bilqis', CURRENT_DATE, 'public/uploads/bilqis/beruang.jpg')
ON CONFLICT DO NOTHING;

-- 5. Enable Row Level Security (RLS) policies (Optional)
ALTER TABLE public."user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Create public access policies for reading data
DROP POLICY IF EXISTS "Allow public read access to projects" ON public.projects;
CREATE POLICY "Allow public read access to projects" ON public.projects
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to user" ON public."user";
CREATE POLICY "Allow public read access to user" ON public."user"
    FOR SELECT USING (true);
