-- ====================================================================
-- PROFESSIONAL SUPABASE POSTGRESQL DATABASE SCHEMA
-- Project: IUDEX Web Portfolio (Enterprise RBAC Edition)
-- ====================================================================

-- Enable UUID extension for secure, unguessable Primary Keys
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- --------------------------------------------------------------------
-- 1. TABLE: team_members (Normalized Member Profiles)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.team_members (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    slug VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(150) NOT NULL,
    bio TEXT,
    avatar_url TEXT,
    facebook_url TEXT,
    instagram_url TEXT,
    linkedin_url TEXT,
    tiktok_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- 2. TABLE: projects (Enhanced Projects Table)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_id UUID DEFAULT gen_random_uuid() UNIQUE,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255),
    description TEXT NOT NULL,
    category VARCHAR(50) DEFAULT 'general',
    status VARCHAR(20) DEFAULT 'published' CHECK (status IN ('draft', 'published', 'archived')),
    member_id UUID REFERENCES public.team_members(id) ON DELETE SET NULL,
    admin VARCHAR(50) NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    image TEXT DEFAULT NULL,
    view_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- 3. TABLE: "user" (Admin Accounts with Role-Based Access Control)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public."user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'admin' CHECK (role IN ('superadmin', 'admin')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure role column exists if table was created earlier
ALTER TABLE public."user" ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'admin';

-- --------------------------------------------------------------------
-- 4. AUTOMATED UPDATED_AT TRIGGER
-- --------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_projects_updated_at ON public.projects;
CREATE TRIGGER trg_projects_updated_at
    BEFORE UPDATE ON public.projects
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- --------------------------------------------------------------------
-- 5. INDEXES
-- --------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_projects_admin ON public.projects(admin);
CREATE INDEX IF NOT EXISTS idx_projects_date ON public.projects(date DESC);
CREATE INDEX IF NOT EXISTS idx_projects_status ON public.projects(status);
CREATE INDEX IF NOT EXISTS idx_user_username ON public."user"(username);

-- --------------------------------------------------------------------
-- 6. ROW LEVEL SECURITY (RLS) POLICIES
-- --------------------------------------------------------------------
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Team Members" ON public.team_members FOR SELECT USING (true);
CREATE POLICY "Admin Modify Team Members" ON public.team_members FOR ALL USING (true);
CREATE POLICY "Public Read Projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Public Insert Projects" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Projects" ON public.projects FOR UPDATE USING (true);
CREATE POLICY "Public Delete Projects" ON public.projects FOR DELETE USING (true);
CREATE POLICY "Public Read Users" ON public."user" FOR SELECT USING (true);
CREATE POLICY "Public Insert Users" ON public."user" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Users" ON public."user" FOR UPDATE USING (true);
CREATE POLICY "Public Delete Users" ON public."user" FOR DELETE USING (true);

-- --------------------------------------------------------------------
-- 7. INITIAL SEED DATA FOR SUPERADMIN ACCOUNT ONLY
-- --------------------------------------------------------------------
INSERT INTO public."user" (username, password, role)
VALUES
    ('superadmin', 'superadmin123', 'superadmin')
ON CONFLICT (username) DO UPDATE SET
    password = EXCLUDED.password,
    role = EXCLUDED.role;

-- --------------------------------------------------------------------
-- 8. SUPABASE STORAGE BUCKET & RLS POLICIES
-- --------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('portfolio-images', 'portfolio-images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Read Portfolio Storage"
ON storage.objects FOR SELECT
USING (bucket_id = 'portfolio-images');

CREATE POLICY "Public Upload Portfolio Storage"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'portfolio-images');

CREATE POLICY "Public Update Portfolio Storage"
ON storage.objects FOR UPDATE
USING (bucket_id = 'portfolio-images');

CREATE POLICY "Public Delete Portfolio Storage"
ON storage.objects FOR DELETE
USING (bucket_id = 'portfolio-images');

SELECT 'Clean Database & Storage Setup Complete!' AS status;


